### ISSUE TITLE
src文件夹下的index.ts和funclib.ts有什么区别 ？

### ISSUE THREAD

**Issue by jacksplwxy** [CN-Tower/funclib.js#1]
后端用index,前端用funclib?

另外，暴露出去fn是不是很容易出现命名冲突？

**Comment by CN-Tower** [comment]
index.js是require或import默认引入的文件，一般nodeJS用的较多，客户端一般用funclib.js或funclib.min.js。默认暴露fn命名空间，类似jQuery的$或lodash的_，可以使用fn.noConflict()释放. :-）
